### ISSUE TITLE
Evaluate new readline implementations

### ISSUE THREAD

**Issue by pkopriv2** [cott-io/iron-releases#12] opened 2018-07-20 15:29 UTC
Our current readline implementation is very spotty across environments.   Many users are experiencing output similar to this:

![image](https://user-images.githubusercontent.com/1661445/43011001-b0fb2bbe-8c07-11e8-98d4-e348eebc7839.png)

We should evaluate other readline implementations or other "prompt" alternatives and estimate the work effort to replace.

AC:
* New readline suggestion
* Work effort estimate

**Comment by zenorseman** [comment] 2018-07-20 15:39
Same results for in terminator, and Ubuntu terminal
Default shell is bash - 4.4.19
![ubuntu_terminal](https://user-images.githubusercontent.com/38734339/43011593-9aca1060-8c09-11e8-94a4-a40b336a6c72.png)
![bashversion](https://user-images.githubusercontent.com/38734339/43011605-9f6285bc-8c09-11e8-86b7-0869f1da0c58.png)
![ubuntu_terminator](https://user-images.githubusercontent.com/38734339/43011611-a27a50cc-8c09-11e8-8150-27c259f1fa0f.png)

**Comment by zenorseman** [comment] 2018-07-20 15:45
Guake doesnt seem to have that issue
![ubuntu_guake](https://user-images.githubusercontent.com/38734339/43011790-143a55b8-8c0a-11e8-8d0d-e7b9166bb5a0.png)

**Comment by zenorseman** [comment] 2018-07-20 16:39
This issue is multiplatform - It is present on Arch, Gentoo, Fedora, openSUSE, Mint, and Ubuntu with KDE, Mate, Cinnamon, and Gnome installed using the pre-installed and configured Terminal programs for the reapective distributions.  If you install guake on these same systems the issue isn't present on guake but it does exist in LXTerminal, Gnome Terminal, Konsole, Mate Terminal, xTerm, and Terminator on these platforms.

**Comment by pkopriv2** [comment] 2018-07-20 19:13
It sounds to me like it's prevalent enough that we should probably do something about it.   I think we should definitely accept this issue and begin researching alternative implementations.

**Comment by pkopriv2** [comment] 2018-07-26 00:20
We have begun working on this issue.  We ended up swapping out the readline implementation with https://github.com/c-bata/go-prompt.  We also evaluated promptui - but it had no facilities for injecting auto completions.   That being said, go-prompt's api is slightly lacking and does a poor job of defining consistent behavior on signal handling (ie ctrl-c does not exit the prompt but produces a new line).   For the time being we're going to fork the implementation and amend it, with a plan to contribute the changes upstream.

**Comment by benhammes** [comment] 2018-08-07 15:12
SPIKE: Moving to database approach.

**Comment by benhammes** [comment] 2018-08-09 15:02
Circular buffer implemented with files.

**Comment by benhammes** [comment] 2018-08-10 14:48
File implementation is more efficient than database.

**Comment by benhammes** [comment] 2018-08-13 15:13
Get update from Manohar and Aadarsh.

**Comment by benhammes** [comment] 2018-08-17 15:06
Still working on it. Working out bugs.

**Comment by benhammes** [comment] 2018-08-23 15:30
Integrating with Tether now.

**Comment by benhammes** [comment] 2018-08-28 15:12
Done it, but sure it is done wrong.

**Comment by benhammes** [comment] 2018-08-29 14:24
Added to Trello.

**Closed as completed by benhammes** 2018-08-29 14:24 UTC
Labels: enhancement
