### ISSUE TITLE
[Improvement] Add first-class windows support

### ISSUE THREAD

**Issue by pkopriv2** [cott-io/iron-releases#13] opened 2018-07-24 19:29 UTC
As a user, I'd like the ability to use all of Iron's tools in a native windows environment, so that I can manage machines across any environment and operating system. 

As a developer, I'd the like the ability to develop natively in Windows, so that I can better provide support for windows users.

AC:
* Local development is fully supported
** Can run all development services natively (messaging and core apis)
* All commands run smoothly.
* Locker is fully supported
* Tether is fully supported

**Comment by josiahconely** [comment] 2018-07-27 21:07
Fe - Native Windows Installation

Install Git on Windows
http://git-scm.com/download/win

1. Install Go
https://golang.org/dl/
Download the latest version of windows-386.msi
Format: “go.<version>.windows-386.msi”

2. Cloning iron-core to local directory
Create the following directory with a single command.
cmd command: ‘mkdir C:\Users\<user>\go\src\github.com\cott-io’.
Clone ‘iron-core’ into above directory after you have the privileges to ‘cott-io/iron-core’ repository.
Navigate to above directory ‘cd C:\Users\<user>\go\src\github.com\cott-io’.
cmd command: ‘git clone https://github.com/cott-io/iron-core’.

3. Glide
Go to ‘https://github.com/Masterminds/glide/releases’.
Download ‘glide-<version>.windows-386.zip
Extract ‘glide.exe’ into ‘<go_root>\bin’ (generally C:\go\bin)
Type "glide install" inside iron-core directory
C:\Users\<user>\go\src\github.com\cott-io\iron-core>glide install
Verify the installation by typing ‘glide’ in cmd

4. Install Environment Variables
Create user variable “GOPATH”, with value - ‘%USERPROFILE%\go’

Create user variable - “GOBIN”  with value - ‘C:\Users\<user>\go\bin’
Edit and Add - ‘%GOPATH%\bin’ under ‘Path’ variable

5. Install Cygwin
Download Cygwin from ‘https://cygwin.com/install.html’
Create a new folder named ‘cygwin64’ in C:\
Move ‘setup-x86_64.exe’ (downloaded file) to C:\cygwin64
Navigate to ‘C:\cygwin64’ directory
C:\cygwin64>setup-x86_64.exe -q -P wget -P gcc-g++ -P make -P diffutils -P libmpfr-devel -P libgmp-devel -P libmpc-devel

Installation help - ‘http://preshing.com/20141108/how-to-install-the-latest-gcc-on-windows/’

6. Install TDM-GCC MinGW Compiler
Download and install "tdm64-gcc-5.1.0-2.exe" from ‘https://sourceforge.net/projects/tdm-gcc/?source=typ_redirect’

Installation - Create: Create a new TDM-GCC installation
Go to Program Files and click on "MinGW Command Prompt". 
This will start a DOS prompt with the correct environment for using MinGW with GCC.

Within this DOS prompt window, navigate to your GOPATH. 
C:\users\<user>\go
Enter the following commands:
go get -u github.com/mattn/go-sqlite3
Then enter:
go install github.com/mattn/go-sqlite3


7. Build your cloned project and add the environment variable
In your command prompt, navigate to your cloned project location
C:\Users\<user>\go\src\github.com\cott-io\iron-core\cmd\fe
Build fe.go using the command 
C:\Users\<user>\go\src\github.com\cott-io\iron-core\cmd\fe>go build fe.go
After this gets executed, add this environment variable so that your system finds fe.exe
‘C:\Users\<user>\go\src\github.com\cott-io\iron-core\cmd\fe’

Run ‘fe’ using the command prompt.

**Comment by josiahconely** [comment] 2018-07-27 21:08
Bugs found: 

when team is disabled, still able to view locker

**Comment by benhammes** [comment] 2018-08-03 15:12
This is a duplicate of issue #12

**Closed as completed by benhammes** 2018-08-03 15:12 UTC
